const MAIN_GENRES = [
    "4X",
    "Action",
    "Action RPG",
    "Adventure",
    "Arcade",
    "Artillery",
    "Audio game",
    "Beat 'em up / brawler",
    "Board game",
    "Card / tile",
    "City building / construction simulation",
    "Dating simulation",
    "Educational",
    "Falling block puzzle",
    "Fangame",
    "Fighting",
    "Hack and slash",
    "Hidden object",
    "Idle",
    "Interactive fiction / text adventure",
    "Japanese-style adventure",
    "Japanese-style RPG (JRPG)",
    "Life / social simulation",
    "Managerial / business simulation",
    "Metroidvania",
    "Music / rhythm",
    "Party game",
    "Pinball",
    "Platform",
    "Puzzle",
    "Racing / Driving",
    "Rail shooter",
    "Real-time strategy (RTS)",
    "Real-time tactics (RTT)",
    "Roguelike",
    "Role-playing (RPG)",
    "Sandbox / open world",
    "Shooter",
    "Simulation",
    "Sports",
    "Stealth",
    "Strategy / tactics",
    "Survival",
    "Survival horror",
    "Tactical RPG",
    "Tactical shooter",
    "Tower defense",
    "Trading / collectible card",
    "Turn-based strategy (TBS)",
    "Turn-based tactics (TBT)",
    "Visual novel",
    "Wargame",
];

const MAIN_PLATFORMS = [
    "PlayStation 3",
    "DOS",
    "Windows",
    "Android",
    "Linux",
    "iPad",
    "PlayStation 4",
    "Xbox One",
    "Xbox 360",
    "iPhone",
    "Commodore 64"

];

const MAIN_COUNTRIES = [
    "United States",
    "Japan",
    "United Kingdom",
    "Canada",
    "Germany",
    "France"
];

module.exports = {
    MAIN_GENRES,
    MAIN_PLATFORMS,
    MAIN_COUNTRIES
}; 